services:
  - type: web
    name: chatgpt-proxy-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python chatgpt_proxy_server.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
